### ISSUE TITLE
Piglet is "waiting for database host"

### ISSUE THREAD

**Issue by manupear** [k3nd0x/piglet#6]
Hi everyone, here's my compose:

```
version: "3.8"
services:
  piglet:
    restart: unless-stopped
    container_name: piglet
    depends_on:
      - database
    ports:
      - 8089:80
      - 8087:8080
    image: k3nd0x/piglet:latest
    networks:
      - shyDockerServer
    environment:
      DB_ROOT_PASSWORD: ${PIGLET_DB_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${MYSQL_DATABASE} # Default 'piglet'
      #MYSQL_USER: ${MYSQL_USER} # Default 'piglet'
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #MYSQL_HOST: ${MYSQL_HOST}
      #MAIL_SERVER: ${MAIL_SERVER}
      #MAIL_USER: ${MAIL_USER}
      #MAIL_PASSWORD: ${MAIL_PASSWORD}
      #MAIL_PORT: ${MAIL_PORT}
      #MAIL_ENCRYPTIONPROTOCOL: ${MAIL_ENCRYPTIONPROTOCOL}
      #DOMAIN: ${DOMAIN} # Default 'localhost'
      #SECURE_COOKIE: ${SECURE_COOKIE}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - swag=enable
      - swag_auth=authelia
  database:
    image: mariadb:latest
    container_name: piglet-db
    volumes:
      - ${DOCKERCONFDIR}/piglet/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PIGLET_DB_ROOT_PASSWORD}

networks:
  shyDockerServer:
    driver: bridge
    external: true
```

And here are the container logs:

- piglet:
```
2023-08-18 00:48:03,154 INFO Set uid to user 0 succeeded
2023-08-18 00:48:03,159 INFO supervisord started with pid 1
2023-08-18 00:48:04,162 INFO spawned: 'import_db' with pid 7
2023-08-18 00:48:04,165 INFO spawned: 'piglet-redis' with pid 8
2023-08-18 00:48:04,168 INFO spawned: 'piglet-api' with pid 9
2023-08-18 00:48:04,171 INFO spawned: 'piglet-app' with pid 10
2023-08-18 00:48:04,187 INFO success: import_db entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
[2023-08-18 00:48:04 +0200] [10] [INFO] Starting gunicorn 21.2.0
[2023-08-18 00:48:04 +0200] [10] [INFO] Listening at: http://0.0.0.0:80 (10)
[2023-08-18 00:48:04 +0200] [10] [INFO] Using worker: sync
[2023-08-18 00:48:04 +0200] [16] [INFO] Booting worker with pid: 16
INFO:     Started server process [9]
INFO:     Waiting for application startup.
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:48:24,212 INFO success: piglet-redis entered RUNNING state, process has stayed up for > than 20 seconds (startsecs)
2023-08-18 00:48:24,214 INFO success: piglet-api entered RUNNING state, process has stayed up for > than 20 seconds (startsecs)
2023-08-18 00:48:24,214 INFO success: piglet-app entered RUNNING state, process has stayed up for > than 20 seconds (startsecs)
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
2023-08-18 00:08:04 waiting for database host
```

- piglet-db:
```
2023-08-14 12:11:09+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-08-14 12:11:10+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-08-14 12:11:10+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-08-14 12:11:12+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
2023-08-14 12:11:12 0 [Note] Starting MariaDB 11.0.2-MariaDB-1:11.0.2+maria~ubu2204 source revision 0005f2f06c8e1aea4915887decad67885108a929 as process 1
2023-08-14 12:11:13 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-08-14 12:11:13 0 [Note] InnoDB: Number of transaction pools: 1
2023-08-14 12:11:13 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2023-08-14 12:11:13 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2023-08-14 12:11:13 0 [Note] InnoDB: Using liburing
2023-08-14 12:11:13 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2023-08-14 12:11:13 0 [Note] InnoDB: Completed initialization of buffer pool
2023-08-14 12:11:13 0 [Note] InnoDB: File system buffers for log disabled (block size=4096 bytes)
2023-08-14 12:11:14 0 [Note] InnoDB: Opened 3 undo tablespaces
2023-08-14 12:11:14 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
2023-08-14 12:11:14 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2023-08-14 12:11:14 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2023-08-14 12:11:14 0 [Note] InnoDB: log sequence number 47897; transaction id 16
2023-08-14 12:11:14 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2023-08-14 12:11:14 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-08-14 12:11:14 0 [Note] Plugin 'wsrep-provider' is disabled.
2023-08-14 12:11:14 0 [Note] Server socket created on IP: '0.0.0.0'.
2023-08-14 12:11:14 0 [Note] Server socket created on IP: '::'.
2023-08-14 12:11:14 0 [Note] InnoDB: Buffer pool(s) load completed at 230814 12:11:14
2023-08-14 12:11:15 0 [Note] mariadbd: ready for connections.
Version: '11.0.2-MariaDB-1:11.0.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

Why doesn't the Piglet main container connect? I've basically used the default compose + some networking stuff.

**Comment by k3nd0x** [comment]
Hi, 
I will test your setup and come back to you soon...

**Comment by k3nd0x** [comment]
I think both containers should be in one network. You only add the piglet container to your shyDockerServer Network. And the piglet db container will get an ip of the default docker network. So they cannot communicate to each other :)

**Comment by manupear** [comment]
> I think both containers should be in one network. You only add the piglet container to your shyDockerServer Network. And the piglet db container will get an ip of the default docker network. So they cannot communicate to each other :)

Ah you're right! I don't know how that escaped my sights, I'll try when I get home and update the issue, thanks

**Comment by manupear** [comment]
It worked, but now I'm having another kind of problem, this happens when I try to create a new user:
```
################################# DEBUG ############################## 4
INFO:     127.0.0.1:55782 - "POST /user/register_user HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/webapp/api/routes/sendmail.py", line 61, in mail
    s = SMTP(host, int(port))
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi    
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__        
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__        
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__     
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__     
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__   
    raise e
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__   
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function       
    return await dependant.call(**values)
  File "/webapp/api/routes/user.py", line 72, in register_user
    mail(payload)
  File "/webapp/api/routes/sendmail.py", line 69, in mail
    except SMTPResponseException as e:
NameError: name 'SMTPResponseException' is not defined
```

And these are the logs for the DB:
```
2023-08-22 12:31:24 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: 
'172.22.0.3' (This connection closed normally without authentication)
2023-08-22 12:31:35 9 [Warning] Aborted connection 9 to db: 'piglet' user: 'piglet' host: '' (Got an error reading communication packets)
2023-08-22 12:32:31 10 [Warning] Aborted connection 10 to db: 'piglet' user: 'piglet' host: '' (Got an error reading communication packets)
2023-08-22 12:34:09 16 [Warning] Aborted connection 16 to db: 'piglet' user: 'piglet' host: '' (Got an error reading communication packets)
```

Any ideas on what I might be doing wrong? The passwords are the same. If this is for another issue, I'll open it and close this :)

**Comment by k3nd0x** [comment]
Ou yes this is another issue. Please create a new one. The app is trying to send a "Email-Verify-Mail" but it can't without config. I have to update the code. But the user was created right?
